import * as users from './users'
import * as train from './train'
import * as common from './common'
import * as basic from './basic'
import * as question from './question'
import * as system from './system'
import * as website from './website'
import * as order from './order'
import * as finance from './finance'
import * as employee from './employee'
import * as safety from './safety'
import * as insure from './insure'
import * as insurebx from './insurebx'
import * as safetysystem from './safetysystem'
import * as trainnew from './trainnew'

export default Object.assign(common, users, train, basic, question, system, website, order, finance,employee,safety,insure,insurebx,safetysystem,trainnew)